Awful.spawn.with_shell("setxkbmap -model abnt2 -layout br")
Awful.spawn.with_shell("feh --bg-scale /home/heitor/Wallpapers/4k/space-1.jpg")
Awful.spawn.with_shell("picom")
Awful.spawn.with_shell("flameshot")
Awful.spawn.with_shell("discord --start-minimized")
